In [3]:
# NumPy 
# Numpy is the foundation of the data science stack
# Pandas dataframes are built on NumPy arrays
# Numpy helps you scale code to millions of rows

# supply chain examples
# numpy can run safety stock calculations over thousands of SKU's in seconds
# numpy can simulate demand and monte carlo analysis by generating random numbers
# matrix operations for optimization using linear algebra


In [4]:
# Drill 1: Creating Arrays
import numpy as np

# create a simple 1-Dimensional Array - showing daily demand for a single SKU
demand = np.array([120, 85, 200, 150, 95, 180, 210])

print(f"Array: {demand}")
print(f"Type: {type(demand)}")
print(f"dtype: {demand.dtype}")
print(f"Shape: {demand.shape}")
print(f"Dimenions: {demand.ndim}")
print(f"Size: {demand.size}")

Array: [120  85 200 150  95 180 210]
Type: <class 'numpy.ndarray'>
dtype: int64
Shape: (7,)
Dimenions: 1
Size: 7


In [5]:
# Drill 2: Array Creation Shortcuts

# Zeros - Initialize an empty inventory array
inventory = np.zeros(7)
print(f"Zeros: {inventory}")

# Ones - Initialize an array with all suppliers at 1
scores = np.ones(5)
print(f"Ones: {scores}")

# Generate a sequence -- np.arange() is inclusive and then exclusive
days = np.arange(start=1, stop=31)
print(f"Days: {days}")

# Generate evenly spaced values between two points
service_levels = np.linspace(start=0.90, stop=0.99, num=5)
print(f"Service levels: {service_levels}")

# Generate random integers meant to simulate lead times
lead_times = np.random.randint(low=3, high=30, size=10)
print(f"Lead times: {lead_times}")

# Generate randome nnumbers to simulate demand variation
# draws random samples from a normal distribution
demand_variation = np.random.normal(loc=100, scale=15, size=30)
print(f"Demand variation (first 5): {demand_variation[:5].round(1)}")

Zeros: [0. 0. 0. 0. 0. 0. 0.]
Ones: [1. 1. 1. 1. 1.]
Days: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
Service levels: [0.9    0.9225 0.945  0.9675 0.99  ]
Lead times: [ 4  3 10 24 25 17 24  7 16 25]
Demand variation (first 5): [105.2  69.8  91.2  80.6 116.6]


In [6]:
# Drill 3
# array[start:stop:step]
# multi-dimensional array[row_slice, column_slice]
# note: numpy slicing ends are EXCLUSIVE --> [:2, :3] --> rows 0 and 1 with columns 0,1,and 2

import numpy as np

# 4x7 demand matrix
demand_matrix = np.array([
    [120, 85, 200, 150, 95, 180, 210],   # SKU-001
    [45,  60, 55,  70,  65, 50,  80],    # SKU-002
    [300, 280, 320, 290, 310, 295, 305], # SKU-003
    [15,  20,  18,  22,  19, 25,  21]    # SKU-004
])

# shape of the demand matrix
print(f"Shape: {demand_matrix}")
print(f"Rows (SKU's): {demand_matrix.shape[0]}")
print(f"Columns (days): {demand_matrix.shape[1]}")
print(f"\nFull matrix:\n{demand_matrix}")

# What does [1, :] mean?
# means select the first row and all columns
print(f"\nSKU-002 daily demand [1,:]: {demand_matrix[1, :]}")

# What does [:, 0] mean?
# means select all rows, and the first column since python is zero-based
print(f"\nAll SKUs day 1 [:, 0]: {demand_matrix[:, 0]}")

# What does [:2, :3] mean?
# means select all rows from 0 to 2 and select all columns from 0 to 3
print(f"\nFirst 2 SKU's, first 3 days [:2, :3]:\n {demand_matrix[:2, :3]}")


Shape: [[120  85 200 150  95 180 210]
 [ 45  60  55  70  65  50  80]
 [300 280 320 290 310 295 305]
 [ 15  20  18  22  19  25  21]]
Rows (SKU's): 4
Columns (days): 7

Full matrix:
[[120  85 200 150  95 180 210]
 [ 45  60  55  70  65  50  80]
 [300 280 320 290 310 295 305]
 [ 15  20  18  22  19  25  21]]

SKU-002 daily demand [1,:]: [45 60 55 70 65 50 80]

All SKUs day 1 [:, 0]: [120  45 300  15]

First 2 SKU's, first 3 days [:2, :3]:
 [[120  85 200]
 [ 45  60  55]]


In [ ]:
# Drill 4
demand - np.array([120, 85, 200, 150, 95, 180, 210])
unit_cost = np.array([25.50, 25.50, 25.50, 25.50, 25.50, 25.50, 25.50])

print(f"Weekly Demand  x2: {demand * 2}")
print(f"Demand + safety buffer: {demand + 50}")
print(f"Demand as % of max: {(demand / demand.max() * 100).round(1)}")

# remember \n is a newline character -- telling python to move to the next line
# {value.format_spec} -- print(f"{x:.1f}")    # 148.7        — 1 decimal place
daily_value = demand * unit_cost
print(f"\nDaily inventory value: {daily_value}")
print(f"\nTotal weekly demand: {demand.sum()}")
print(f"Average daily demand: {demand.mean():.1f}")
print(f"Peak demand day: {demand.max()}")
print(f"Lowest demand day: {demand.min()}")
print(f"Std Deviation: {demand.std():.1f}")

Weekly Demand  x2: [240 170 400 300 190 360 420]
Demand + safety buffer: [170 135 250 200 145 230 260]
Demand as % of max: [ 57.1  40.5  95.2  71.4  45.2  85.7 100. ]

Daily inventory value: [3060.  2167.5 5100.  3825.  2422.5 4590.  5355. ]

Total weekly demand: 1040
Average daily demand: 148.6
Peak demand day: 210
Lowest demand day: 85
Std Deviation: 46.5
