In [3]:
# NumPy 
# Numpy is the foundation of the data science stack
# Pandas dataframes are built on NumPy arrays
# Numpy helps you scale code to millions of rows

# supply chain examples
# numpy can run safety stock calculations over thousands of SKU's in seconds
# numpy can simulate demand and monte carlo analysis by generating random numbers
# matrix operations for optimization using linear algebra


In [4]:
# Drill 1: Creating Arrays
import numpy as np

# create a simple 1-Dimensional Array - showing daily demand for a single SKU
demand = np.array([120, 85, 200, 150, 95, 180, 210])

print(f"Array: {demand}")
print(f"Type: {type(demand)}")
print(f"dtype: {demand.dtype}")
print(f"Shape: {demand.shape}")
print(f"Dimenions: {demand.ndim}")
print(f"Size: {demand.size}")

Array: [120  85 200 150  95 180 210]
Type: <class 'numpy.ndarray'>
dtype: int64
Shape: (7,)
Dimenions: 1
Size: 7


In [5]:
# Drill 2: Array Creation Shortcuts

# Zeros - Initialize an empty inventory array
inventory = np.zeros(7)
print(f"Zeros: {inventory}")

# Ones - Initialize an array with all suppliers at 1
scores = np.ones(5)
print(f"Ones: {scores}")

# Generate a sequence -- np.arange() is inclusive and then exclusive
days = np.arange(start=1, stop=31)
print(f"Days: {days}")

# Generate evenly spaced values between two points
service_levels = np.linspace(start=0.90, stop=0.99, num=5)
print(f"Service levels: {service_levels}")

# Generate random integers meant to simulate lead times
lead_times = np.random.randint(low=3, high=30, size=10)
print(f"Lead times: {lead_times}")

# Generate randome nnumbers to simulate demand variation
# draws random samples from a normal distribution
demand_variation = np.random.normal(loc=100, scale=15, size=30)
print(f"Demand variation (first 5): {demand_variation[:5].round(1)}")

Zeros: [0. 0. 0. 0. 0. 0. 0.]
Ones: [1. 1. 1. 1. 1.]
Days: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
Service levels: [0.9    0.9225 0.945  0.9675 0.99  ]
Lead times: [ 4  3 10 24 25 17 24  7 16 25]
Demand variation (first 5): [105.2  69.8  91.2  80.6 116.6]


In [6]:
# Drill 3
# array[start:stop:step]
# multi-dimensional array[row_slice, column_slice]
# note: numpy slicing ends are EXCLUSIVE --> [:2, :3] --> rows 0 and 1 with columns 0,1,and 2

import numpy as np

# 4x7 demand matrix
demand_matrix = np.array([
    [120, 85, 200, 150, 95, 180, 210],   # SKU-001
    [45,  60, 55,  70,  65, 50,  80],    # SKU-002
    [300, 280, 320, 290, 310, 295, 305], # SKU-003
    [15,  20,  18,  22,  19, 25,  21]    # SKU-004
])

# shape of the demand matrix
print(f"Shape: {demand_matrix}")
print(f"Rows (SKU's): {demand_matrix.shape[0]}")
print(f"Columns (days): {demand_matrix.shape[1]}")
print(f"\nFull matrix:\n{demand_matrix}")

# What does [1, :] mean?
# means select the first row and all columns
print(f"\nSKU-002 daily demand [1,:]: {demand_matrix[1, :]}")

# What does [:, 0] mean?
# means select all rows, and the first column since python is zero-based
print(f"\nAll SKUs day 1 [:, 0]: {demand_matrix[:, 0]}")

# What does [:2, :3] mean?
# means select all rows from 0 to 2 and select all columns from 0 to 3
print(f"\nFirst 2 SKU's, first 3 days [:2, :3]:\n {demand_matrix[:2, :3]}")


Shape: [[120  85 200 150  95 180 210]
 [ 45  60  55  70  65  50  80]
 [300 280 320 290 310 295 305]
 [ 15  20  18  22  19  25  21]]
Rows (SKU's): 4
Columns (days): 7

Full matrix:
[[120  85 200 150  95 180 210]
 [ 45  60  55  70  65  50  80]
 [300 280 320 290 310 295 305]
 [ 15  20  18  22  19  25  21]]

SKU-002 daily demand [1,:]: [45 60 55 70 65 50 80]

All SKUs day 1 [:, 0]: [120  45 300  15]

First 2 SKU's, first 3 days [:2, :3]:
 [[120  85 200]
 [ 45  60  55]]


In [ ]:
# Drill 4
demand = np.array([120, 85, 200, 150, 95, 180, 210])
unit_cost = np.array([25.50, 25.50, 25.50, 25.50, 25.50, 25.50, 25.50])

print(f"Weekly Demand  x2: {demand * 2}")
print(f"Demand + safety buffer: {demand + 50}")
print(f"Demand as % of max: {(demand / demand.max() * 100).round(1)}")

# remember \n is a newline character -- telling python to move to the next line
# {value.format_spec} -- print(f"{x:.1f}")    # 148.7        — 1 decimal place
daily_value = demand * unit_cost
print(f"\nDaily inventory value: {daily_value}")
print(f"\nTotal weekly demand: {demand.sum()}")
print(f"Average daily demand: {demand.mean():.1f}")
print(f"Peak demand day: {demand.max()}")
print(f"Lowest demand day: {demand.min()}")
print(f"Std Deviation: {demand.std():.1f}")

# why is demand * 2 faster than a loop?
# loops interpret each element one at a time
# numpy processes using vectorized operations 

Weekly Demand  x2: [240 170 400 300 190 360 420]
Demand + safety buffer: [170 135 250 200 145 230 260]
Demand as % of max: [ 57.1  40.5  95.2  71.4  45.2  85.7 100. ]

Daily inventory value: [3060.  2167.5 5100.  3825.  2422.5 4590.  5355. ]

Total weekly demand: 1040
Average daily demand: 148.6
Peak demand day: 210
Lowest demand day: 85
Std Deviation: 46.5


## Drill 5 - Boolean Indexing
- pandas uses `df[df["col"] > value]`
- numpy uses a similar pattern

In [7]:
import numpy as np
demand = np.array([120, 45, 300, 0, 88, 210, 55, 175, 400, 30])
unit_cost = np.array([25.50, 42.00, 15.75, 15.75, 8.25, 8.25,
                      32.00, 18.50, 5.10, 5.10])

# which sku's have demand > 100
# create a mask
high_demand_mask = demand > 100
print(f"Boolean mask: {high_demand_mask}")

# apply the mask - returning only high demand values
high_demand = demand[high_demand_mask]
print(f"High demand SKU's: {high_demand}")

# complete the previous steps in a single-line
print(f"In one line:{demand[demand > 100]}")

# write a compound condition
affordable_high_dem = demand[(demand > 50) & (unit_cost < 20)]
print(f"High demand, low cost: {affordable_high_dem}")

# use np.where() to return index positions noting where the condition is true
high_demand_idx = np.where(demand > 100)
print(f"Indices where demand > 100: {high_demand_idx}")

# use np.where with conditions, critical if demand = 0, "ok" otherwise
status = np.where(demand == 0, "critical", "ok")
print(f"Stock status: {status}")

Boolean mask: [ True False  True False False  True False  True  True False]
High demand SKU's: [120 300 210 175 400]
In one line:[120 300 210 175 400]
High demand, low cost: [300  88 210 175 400]
Indices where demand > 100: (array([0, 2, 5, 7, 8]),)
Stock status: ['ok' 'ok' 'ok' 'critical' 'ok' 'ok' 'ok' 'ok' 'ok' 'ok']


In [ ]:
# Drill 6: Array Reshaping
import numpy as np
# monthly demand values -- (12 rows, 0 columns)
monthly = np.array([120, 85, 200, 150, 95, 180,
                    210, 165, 245, 130, 175, 220])

# get the shape of the data (row,col)
print(f"Original shape: {monthly.shape}")
print(f"Original:\n{monthly}")

# reshape from (12,0) to (3,4)
quarterly = monthly.reshape(3,4)
print(f"\nReshaped to 3x4 (quarters x months):\n{quarterly}")

# reshape from (3,4) to (4,3)
by_quarter = monthly.reshape(4,3)
print(f"\nReshaped to 4 x 3:\n{by_quarter}")

# flatten back to one-dimension
flat = quarterly.flatten()
print(f"\nFlattened back: {flat}")

# use numpy to calculate the missing dimension
# the "-1" tells NumPy to figure out this dimension automatically based on the total number of elements
# and the other dimensions specified
auto = monthly.reshape(2, -1)
print(f"\nReshaped with -1 (2, auto):\n {auto}")
print(f"\nShape of auto:\n {auto.shape}")

Original shape: (12,)
Original:
[120  85 200 150  95 180 210 165 245 130 175 220]

Reshaped to 3x4 (quarters x months):
[[120  85 200 150]
 [ 95 180 210 165]
 [245 130 175 220]]

Reshaped to 4 x 3:
[[120  85 200]
 [150  95 180]
 [210 165 245]
 [130 175 220]]

Flattened back: [120  85 200 150  95 180 210 165 245 130 175 220]

Reshaped with -1 (2, auto):
 [[120  85 200 150  95 180]
 [210 165 245 130 175 220]]

Shape of auto:
 (2, 6)


In [ ]:
# Drill 7: Axis Aggregation

import numpy as np

# create the array of data
# 4SKU's x 7 days

demand_matrix = np.array([
    [120, 85, 200, 150, 95, 180, 210],   # SKU-001
    [45,  60, 55,  70,  65, 50,  80],    # SKU-002
    [300, 280, 320, 290, 310, 295, 305], # SKU-003
    [15,  20,  18,  22,  19, 25,  21]    # SKU-004
])

# axis=0 aggregates DOWN the columns
daily_total = demand_matrix.sum(axis=0)
print(f"Total demand per day (axis=0): {daily_total}")

# axis=1 aggregates across the rows
sku_total = demand_matrix.sum(axis=1)
print(f"Total demand per SKU: {sku_total}")

# find the mean per sku
sku_mean = demand_matrix.mean(axis=1).round(1)
print(f"Average daily demand per SKU: {sku_mean}")

# max demand for each sku
sku_peak = demand_matrix.max(axis=1)
print(f"Peak demand per SKU: {sku_peak}")

# which day had the highest demand for each SKU?
peak_day = demand_matrix.argmax(axis=1)
print(f"Peak demand day index per SKU: {peak_day}")

# normalize each SKU's daily demand as a % of its own total
# keepdims=True preserves the original number of dimensions after aggregating so (4, ) becomes (4,1)
normalized = (demand_matrix / demand_matrix.sum(axis=1, keepdims=True))
print(f"\nNormalized demand (% of SKU total):\n{normalized}")

Total demand per day (axis=0): [480 445 593 532 489 550 616]
Total demand per SKU: [1040  425 2100  140]
Average daily demand per SKU: [148.6  60.7 300.   20. ]
Peak demand per SKU: [210  80 320  25]
Peak demand day index per SKU: [6 6 2 5]

Normalized demand (% of SKU total):
[[0.11538462 0.08173077 0.19230769 0.14423077 0.09134615 0.17307692
  0.20192308]
 [0.10588235 0.14117647 0.12941176 0.16470588 0.15294118 0.11764706
  0.18823529]
 [0.14285714 0.13333333 0.15238095 0.13809524 0.14761905 0.14047619
  0.1452381 ]
 [0.10714286 0.14285714 0.12857143 0.15714286 0.13571429 0.17857143
  0.15      ]]


In [ ]:
# Drill 8: Safety Stock Formula using NumPy
# Formula: Safety Stock = ZScore * SD_Demand * SQRT(Lead_Time)

# create the datasets
# SC dataset — 8 SKUs
sku_ids = np.array(["SKU-001", "SKU-002", "SKU-003", "SKU-004",
                    "SKU-005", "SKU-006", "SKU-007", "SKU-008"])

# service level z-scores
Z_SCORES = {0.90: 1.28, 0.95: 1.65, 0.99: 2.33}

daily_demand = np.array([120.0, 45.0, 300.0, 0.0, 88.0, 210.0, 55.0, 175.0])
demand_std   = np.array([15.2, 8.1, 42.3, 0.0, 12.5, 28.7, 9.3, 22.1])
lead_time    = np.array([14, 7, 21, 10, 5, 30, 12, 18])

# vectorize the function
# note: safety stock needs to always round up, for example 92.3 units, should round up to 93 to avoid shortages
def calculate_safety_stock(demand_std, lead_time, service_level=0.95):
    z = Z_SCORES[service_level]
    return np.ceil(z * demand_std * np.sqrt(lead_time)).astype(int)

# calculate the 95% service level
ss_95 = calculate_safety_stock(demand_std, lead_time, service_level=0.95)
print(f"Safety stock (95% Service Level):\n{ss_95}")

# calculate for all three service levels
for level, z in Z_SCORES.items():
    ss = calculate_safety_stock(demand_std, lead_time, service_level=level)
    print(f"\nService level {level*100: .0f}%:")
    for sku, stock in zip(sku_ids, ss):
        print(f"  {sku}: {stock} units")

# reorder point = safety stock + average demand during lead time
avg_demand_during_lt = daily_demand * lead_time
reorder_point = ss_95 + avg_demand_during_lt
print(f"\nReorder points (95% service level):\n {reorder_point.astype(int)}")

Safety stock (95% Service Level):
[ 94  36 320   0  47 260  54 155]

Service level  90%:
  SKU-001: 73 units
  SKU-002: 28 units
  SKU-003: 249 units
  SKU-004: 0 units
  SKU-005: 36 units
  SKU-006: 202 units
  SKU-007: 42 units
  SKU-008: 121 units

Service level  95%:
  SKU-001: 94 units
  SKU-002: 36 units
  SKU-003: 320 units
  SKU-004: 0 units
  SKU-005: 47 units
  SKU-006: 260 units
  SKU-007: 54 units
  SKU-008: 155 units

Service level  99%:
  SKU-001: 133 units
  SKU-002: 50 units
  SKU-003: 452 units
  SKU-004: 0 units
  SKU-005: 66 units
  SKU-006: 367 units
  SKU-007: 76 units
  SKU-008: 219 units

Reorder points (95% service level):
 [1774  351 6620    0  487 6560  714 3305]
